### ISSUE TITLE
Remove splitrom?

### ISSUE THREAD

**Issue by Clownacy** [sonicretro/s2disasm#22]
Ever since I added REV00, there have been some files in the disassembly that split.bat can't produce, since it depends on a REV01 ROM. I could get creative, and make a second s2.txt specifically for REV00, to get the last few files, but I don't think the thing's worth the maintenance burden anymore.

This disasm already comes with the files pre-split, and the only reason to not include the binaries is as a very weak legal defence.

So, anyone else got any input?

**Comment by flamewing** [comment]
There is another very well reason: so that someone that did a layout hack in hex can take splitrom as reference and extract the modified data into the S2 disassembly. It is a very weak reason, especially when you factor in how many people stubbornly refuse to use the git version, which makes the likelihood of someone using the git disasm for this reason very slim.

Consider now that it can wreck a hack if you are a novice (and do not use version control very effectively), and I am all in favor of removing it.

Maybe it would be worth to split the tool into a separate repository.

**Comment by MainMemory** [comment]
Don't SonED and ESE move the layout data to another part of the ROM anyway?

**Comment by flamewing** [comment]
Splitrom does take in a text file of offsets which can be modified as appropriate.
