### ISSUE TITLE
Convert sprite mappings to assembly(?)

### ISSUE THREAD

**Issue by Brainulator9** [sonicretro/s2disasm#47]
This is probably going to be a bit controversial, but I really don't like how most sprite mappings are included as binary files in this disassembly rather than as assembly, for a few reasons:

- Our disassemblies of Sonic 1 and Sonic 3 & Knuckles have their mappings stored as assembly files, leaving this one on its own despite Sonic 1, 2, and 3/K all being based on the same code.
- The splitting into binary is said in the main disassembly file to have been done to aid external mapping editor programs. This makes sense as far as the splitting goes, but SonMapEd and Flex 2 both support assembly-based mappings.
- We know the original source code implemented these mappings in assembly (though the details as to how exactly they were implemented are unclear), given that certain mappings are not straightforward as our programs would assume. Some call for an incorrect number of pieces, some are included in the ROM in a different order than they are listed in each offset table, some mappings appear in multiple offset tables, some offset tables draw from multiple mappings lists, some use negative tile offsets, and some refer to the same mapping frame multiple times. In addition, labels found within the Sonic 2 Nick Arcade prototype's leftover data include symbols for the individual frames.
- There is precedent for converting binary data into assembly data in this disassembly, namely the music and sound effects. Those, too, are known to have been originally assembled, only this time by virtue of released source code for a different version of this game's sound program.

How exactly to implement this, if accepted, may need more discussion.

**Comment by Clownacy** [comment]
I agree with this. As for how it's done, while portable mapping macros would be ideal, they're not as universally supported as raw assembly mappings, so I think we should start with just plain assembly mappings and then gradually transition to macros as it becomes more feasible.

By the way, there was indication that SMPS used assembly for its music and sound effects long before its source code was found, as SMPS Z80 music and SFX contain absolute addresses that could only be determined at build-time. That's why Sonic 2's 2007 Xenowhirl disassembly stores the SFX as assembly: because otherwise moving the data would break it.

**Comment by Clownacy** [comment]
Mappings and DPLCs have been migrated to MapMacros as of 5ca0f3a850806920d2be199d077c8ef1babd3b80.

**Comment by MainMemory** [comment]
Wow, RIP sprite editors I guess. Are there even any tools that support the macros other than SonLVL and my converters?

**Comment by Clownacy** [comment]
ClownMapEd gained support for them in [its latest update](https://github.com/Clownacy/clownmaped/releases/tag/v1.1). Also I thought Flex2 supported them?

**Comment by MainMemory** [comment]
I was talking to snkenjoi about it years ago, but I never saw if it was actually implemented.
