### ISSUE TITLE
i can't load the sprite Maps & pattern cues

### ISSUE THREAD

**Issue by CHUCKECHEESETubeYT** [sonicretro/s2disasm#56]
whenever I try to load in Sonic 2 Sprite maps and pattern cues it just won't load! do you have any advice?

**Comment by FourHawk** [comment]
If you're using a program like SonMapEd then it will not work due to the mappings format used by this disasm (And the Sonic 1 disasm) being updated to a macro based one, ether use a sprite editor like [Flex2](https://github.com/kirjavascript/Flex2) or if you want a more modern based editor that feels like SonMapEd, there is [ClownMapEd](https://github.com/Clownacy/clownmaped).

**Comment by CHUCKECHEESETubeYT** [comment]
what are you talking about?

**Comment by FourHawk** [comment]
Ok i should have started from the top, What are you using to load the sprites?

**Comment by CHUCKECHEESETubeYT** [comment]
SonMapEd

**Comment by FourHawk** [comment]
Well there's your problem, SonMapEd is outdated and doesn't work anymore with the sonic 2 disasm, please use a newer sprite editor like [Flex2](https://github.com/kirjavascript/Flex2) or [ClownMapEd ](https://github.com/Clownacy/clownmaped)
